application: aerobic-datum-94820
#application: intro-to-programming-app
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /styles
  static_dir: styles

- url: /images
  static_dir: images

#- url: /.*
- url: .*
  script: coursenotes.app

libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: latest